import React from 'react';
import { storiesOf } from '@storybook/react';

import styled from 'styled-components';

import { boolean, text, select } from '@storybook/addon-knobs';

import Accordion from './Accordion';

import Text from '../Text/Text';

storiesOf('Base|Accordion', module)
  .add('Default', () => (
    <div>
      <Accordion>
        <ExampleContent>
          <Text variant="hero" weight="700">
            Quisque adipiscing
          </Text>
          <Text variant="baseline">
            Quisque adipiscing suspendisse mus magnis scelerisque leo vulputate ullamcorper molestie in a condimentum a ac risus dictumst cum a imperdiet duis a. Primis mi erat sociosqu fringilla in cum maecenas et porta ridiculus lobortis morbi suspendisse maecenas hac dictumst dis parturient phasellus primis vestibulum a condimentum. Suscipit a placerat metus scelerisque senectus sodales ullamcorper tellus a sem senectus sed porta eleifend quam consectetur leo adipiscing curae ullamcorper erat vestibulum mauris leo quisque vestibulum id. Etiam gravida ultricies neque netus torquent tristique varius nostra sociis libero adipiscing vestibulum suspendisse scelerisque tincidunt. Facilisi nascetur laoreet eleifend adipiscing amet lobortis lacus vehicula integer scelerisque a litora a integer ullamcorper fusce pulvinar ullamcorper ad eu. Id quis consequat venenatis suspendisse a ad turpis quam tortor id suspendisse in a venenatis sed non. Massa inceptos ante condimentum sit scelerisque ac nisl pharetra a et vestibulum cras vestibulum erat sit ad penatibus sodales blandit est dis a. Sociosqu porttitor a praesent sagittis scelerisque ad ad eu orci parturient elit tincidunt et condimentum a pretium vestibulum hendrerit a molestie blandit enim at parturient accumsan. A fermentum suspendisse class facilisis convallis cubilia quisque sociis a a vestibulum integer a class a. Scelerisque pretium a magnis id suspendisse sodales cum non cubilia parturient himenaeos sit a quisque platea magna nostra enim cras suspendisse a mi adipiscing.Consectetur a inceptos accumsan donec varius elementum conubia nec varius mi congue curabitur ante a at hac cras.Condimentum vestibulum consectetur habitant eleifend dignissim malesuada taciti a sagittis porta velit nunc elementum orci mus bibendum quisque felis sodales faucibus vehicula scelerisque a parturient.Ac hendrerit vehicula ullamcorper a parturient a quis quisque suspendisse volutpat a hac sociosqu nisl posuere mus pulvinar commodo a ullamcorper vestibulum morbi.Quis ad congue metus iaculis iaculis accumsan pretium orci vestibulum laoreet scelerisque fusce ultricies inceptos pretium consectetur.
          </Text>
          <Text variant="title" weight="700">
            Suspendisse mus magnis
          </Text>
          <Text variant="large">
            Quisque adipiscing suspendisse mus magnis scelerisque leo vulputate ullamcorper molestie in a condimentum a ac risus dictumst cum a imperdiet duis a. Primis mi erat sociosqu fringilla in cum maecenas et porta ridiculus lobortis morbi suspendisse maecenas hac dictumst dis parturient phasellus primis vestibulum a condimentum. Suscipit a placerat metus scelerisque senectus sodales ullamcorper tellus a sem senectus sed porta eleifend quam consectetur leo adipiscing curae ullamcorper erat vestibulum mauris leo quisque vestibulum id. Etiam gravida ultricies neque netus torquent tristique varius nostra sociis libero adipiscing vestibulum suspendisse scelerisque tincidunt. Facilisi nascetur laoreet eleifend adipiscing amet lobortis lacus vehicula integer scelerisque a litora a integer ullamcorper fusce pulvinar ullamcorper ad eu. Id quis consequat venenatis suspendisse a ad turpis quam tortor id suspendisse in a venenatis sed non. Massa inceptos ante condimentum sit scelerisque ac nisl pharetra a et vestibulum cras vestibulum erat sit ad penatibus sodales blandit est dis a. Sociosqu porttitor a praesent sagittis scelerisque ad ad eu orci parturient elit tincidunt et condimentum a pretium vestibulum hendrerit a molestie blandit enim at parturient accumsan. A fermentum suspendisse class facilisis convallis cubilia quisque sociis a a vestibulum integer a class a. Scelerisque pretium a magnis id suspendisse sodales cum non cubilia parturient himenaeos sit a quisque platea magna nostra enim cras suspendisse a mi adipiscing.Consectetur a inceptos accumsan donec varius elementum conubia nec varius mi congue curabitur ante a at hac cras.Condimentum vestibulum consectetur habitant eleifend dignissim malesuada taciti a sagittis porta velit nunc elementum orci mus bibendum quisque felis sodales faucibus vehicula scelerisque a parturient.Ac hendrerit vehicula ullamcorper a parturient a quis quisque suspendisse volutpat a hac sociosqu nisl posuere mus pulvinar commodo a ullamcorper vestibulum morbi.Quis ad congue metus iaculis iaculis accumsan pretium orci vestibulum laoreet scelerisque fusce ultricies inceptos pretium consectetur.
          </Text>
          <Text variant="subtitle1" weight="700">
            Leo vulputate ullamcorper
          </Text>
          <Text variant="baseline">
            Quisque adipiscing suspendisse mus magnis scelerisque leo vulputate ullamcorper molestie in a condimentum a ac risus dictumst cum a imperdiet duis a. Primis mi erat sociosqu fringilla in cum maecenas et porta ridiculus lobortis morbi suspendisse maecenas hac dictumst dis parturient phasellus primis vestibulum a condimentum. Suscipit a placerat metus scelerisque senectus sodales ullamcorper tellus a sem senectus sed porta eleifend quam consectetur leo adipiscing curae ullamcorper erat vestibulum mauris leo quisque vestibulum id. Etiam gravida ultricies neque netus torquent tristique varius nostra sociis libero adipiscing vestibulum suspendisse scelerisque tincidunt. Facilisi nascetur laoreet eleifend adipiscing amet lobortis lacus vehicula integer scelerisque a litora a integer ullamcorper fusce pulvinar ullamcorper ad eu. Id quis consequat venenatis suspendisse a ad turpis quam tortor id suspendisse in a venenatis sed non. Massa inceptos ante condimentum sit scelerisque ac nisl pharetra a et vestibulum cras vestibulum erat sit ad penatibus sodales blandit est dis a. Sociosqu porttitor a praesent sagittis scelerisque ad ad eu orci parturient elit tincidunt et condimentum a pretium vestibulum hendrerit a molestie blandit enim at parturient accumsan. A fermentum suspendisse class facilisis convallis cubilia quisque sociis a a vestibulum integer a class a. Scelerisque pretium a magnis id suspendisse sodales cum non cubilia parturient himenaeos sit a quisque platea magna nostra enim cras suspendisse a mi adipiscing.Consectetur a inceptos accumsan donec varius elementum conubia nec varius mi congue curabitur ante a at hac cras.Condimentum vestibulum consectetur habitant eleifend dignissim malesuada taciti a sagittis porta velit nunc elementum orci mus bibendum quisque felis sodales faucibus vehicula scelerisque a parturient.Ac hendrerit vehicula ullamcorper a parturient a quis quisque suspendisse volutpat a hac sociosqu nisl posuere mus pulvinar commodo a ullamcorper vestibulum morbi.Quis ad congue metus iaculis iaculis accumsan pretium orci vestibulum laoreet scelerisque fusce ultricies inceptos pretium consectetur.
          </Text>
          <Text variant="subtitle2" weight="700">
            Condimentum a ac risus dictumst
          </Text>
          <Text variant="baseline">
            Quisque adipiscing suspendisse mus magnis scelerisque leo vulputate ullamcorper molestie in a condimentum a ac risus dictumst cum a imperdiet duis a. Primis mi erat sociosqu fringilla in cum maecenas et porta ridiculus lobortis morbi suspendisse maecenas hac dictumst dis parturient phasellus primis vestibulum a condimentum. Suscipit a placerat metus scelerisque senectus sodales ullamcorper tellus a sem senectus sed porta eleifend quam consectetur leo adipiscing curae ullamcorper erat vestibulum mauris leo quisque vestibulum id. Etiam gravida ultricies neque netus torquent tristique varius nostra sociis libero adipiscing vestibulum suspendisse scelerisque tincidunt. Facilisi nascetur laoreet eleifend adipiscing amet lobortis lacus vehicula integer scelerisque a litora a integer ullamcorper fusce pulvinar ullamcorper ad eu. Id quis consequat venenatis suspendisse a ad turpis quam tortor id suspendisse in a venenatis sed non. Massa inceptos ante condimentum sit scelerisque ac nisl pharetra a et vestibulum cras vestibulum erat sit ad penatibus sodales blandit est dis a. Sociosqu porttitor a praesent sagittis scelerisque ad ad eu orci parturient elit tincidunt et condimentum a pretium vestibulum hendrerit a molestie blandit enim at parturient accumsan. A fermentum suspendisse class facilisis convallis cubilia quisque sociis a a vestibulum integer a class a. Scelerisque pretium a magnis id suspendisse sodales cum non cubilia parturient himenaeos sit a quisque platea magna nostra enim cras suspendisse a mi adipiscing.Consectetur a inceptos accumsan donec varius elementum conubia nec varius mi congue curabitur ante a at hac cras.Condimentum vestibulum consectetur habitant eleifend dignissim malesuada taciti a sagittis porta velit nunc elementum orci mus bibendum quisque felis sodales faucibus vehicula scelerisque a parturient.Ac hendrerit vehicula ullamcorper a parturient a quis quisque suspendisse volutpat a hac sociosqu nisl posuere mus pulvinar commodo a ullamcorper vestibulum morbi.Quis ad congue metus iaculis iaculis accumsan pretium orci vestibulum laoreet scelerisque fusce ultricies inceptos pretium consectetur.
          </Text>
          <Text variant="baseline">
            Quisque adipiscing suspendisse mus magnis scelerisque leo vulputate ullamcorper molestie in a condimentum a ac risus dictumst cum a imperdiet duis a. Primis mi erat sociosqu fringilla in cum maecenas et porta ridiculus lobortis morbi suspendisse maecenas hac dictumst dis parturient phasellus primis vestibulum a condimentum. Suscipit a placerat metus scelerisque senectus sodales ullamcorper tellus a sem senectus sed porta eleifend quam consectetur leo adipiscing curae ullamcorper erat vestibulum mauris leo quisque vestibulum id. Etiam gravida ultricies neque netus torquent tristique varius nostra sociis libero adipiscing vestibulum suspendisse scelerisque tincidunt. Facilisi nascetur laoreet eleifend adipiscing amet lobortis lacus vehicula integer scelerisque a litora a integer ullamcorper fusce pulvinar ullamcorper ad eu. Id quis consequat venenatis suspendisse a ad turpis quam tortor id suspendisse in a venenatis sed non. Massa inceptos ante condimentum sit scelerisque ac nisl pharetra a et vestibulum cras vestibulum erat sit ad penatibus sodales blandit est dis a. Sociosqu porttitor a praesent sagittis scelerisque ad ad eu orci parturient elit tincidunt et condimentum a pretium vestibulum hendrerit a molestie blandit enim at parturient accumsan. A fermentum suspendisse class facilisis convallis cubilia quisque sociis a a vestibulum integer a class a. Scelerisque pretium a magnis id suspendisse sodales cum non cubilia parturient himenaeos sit a quisque platea magna nostra enim cras suspendisse a mi adipiscing.Consectetur a inceptos accumsan donec varius elementum conubia nec varius mi congue curabitur ante a at hac cras.Condimentum vestibulum consectetur habitant eleifend dignissim malesuada taciti a sagittis porta velit nunc elementum orci mus bibendum quisque felis sodales faucibus vehicula scelerisque a parturient.Ac hendrerit vehicula ullamcorper a parturient a quis quisque suspendisse volutpat a hac sociosqu nisl posuere mus pulvinar commodo a ullamcorper vestibulum morbi.Quis ad congue metus iaculis iaculis accumsan pretium orci vestibulum laoreet scelerisque fusce ultricies inceptos pretium consectetur.
          </Text>
         </ExampleContent>
      </Accordion>
      <Accordion expandByDefault>
        <ExampleContent>
          <Text variant="hero" weight="700">
            Quisque adipiscing
          </Text>
          <Text variant="baseline">
            Quisque adipiscing suspendisse mus magnis scelerisque leo vulputate ullamcorper molestie in a condimentum a ac risus dictumst cum a imperdiet duis a. Primis mi erat sociosqu fringilla in cum maecenas et porta ridiculus lobortis morbi suspendisse maecenas hac dictumst dis parturient phasellus primis vestibulum a condimentum. Suscipit a placerat metus scelerisque senectus sodales ullamcorper tellus a sem senectus sed porta eleifend quam consectetur leo adipiscing curae ullamcorper erat vestibulum mauris leo quisque vestibulum id. Etiam gravida ultricies neque netus torquent tristique varius nostra sociis libero adipiscing vestibulum suspendisse scelerisque tincidunt. Facilisi nascetur laoreet eleifend adipiscing amet lobortis lacus vehicula integer scelerisque a litora a integer ullamcorper fusce pulvinar ullamcorper ad eu. Id quis consequat venenatis suspendisse a ad turpis quam tortor id suspendisse in a venenatis sed non. Massa inceptos ante condimentum sit scelerisque ac nisl pharetra a et vestibulum cras vestibulum erat sit ad penatibus sodales blandit est dis a. Sociosqu porttitor a praesent sagittis scelerisque ad ad eu orci parturient elit tincidunt et condimentum a pretium vestibulum hendrerit a molestie blandit enim at parturient accumsan. A fermentum suspendisse class facilisis convallis cubilia quisque sociis a a vestibulum integer a class a. Scelerisque pretium a magnis id suspendisse sodales cum non cubilia parturient himenaeos sit a quisque platea magna nostra enim cras suspendisse a mi adipiscing.Consectetur a inceptos accumsan donec varius elementum conubia nec varius mi congue curabitur ante a at hac cras.Condimentum vestibulum consectetur habitant eleifend dignissim malesuada taciti a sagittis porta velit nunc elementum orci mus bibendum quisque felis sodales faucibus vehicula scelerisque a parturient.Ac hendrerit vehicula ullamcorper a parturient a quis quisque suspendisse volutpat a hac sociosqu nisl posuere mus pulvinar commodo a ullamcorper vestibulum morbi.Quis ad congue metus iaculis iaculis accumsan pretium orci vestibulum laoreet scelerisque fusce ultricies inceptos pretium consectetur.
          </Text>
          <Text variant="title" weight="700">
            Suspendisse mus magnis
          </Text>
          <Text variant="large">
            Quisque adipiscing suspendisse mus magnis scelerisque leo vulputate ullamcorper molestie in a condimentum a ac risus dictumst cum a imperdiet duis a. Primis mi erat sociosqu fringilla in cum maecenas et porta ridiculus lobortis morbi suspendisse maecenas hac dictumst dis parturient phasellus primis vestibulum a condimentum. Suscipit a placerat metus scelerisque senectus sodales ullamcorper tellus a sem senectus sed porta eleifend quam consectetur leo adipiscing curae ullamcorper erat vestibulum mauris leo quisque vestibulum id. Etiam gravida ultricies neque netus torquent tristique varius nostra sociis libero adipiscing vestibulum suspendisse scelerisque tincidunt. Facilisi nascetur laoreet eleifend adipiscing amet lobortis lacus vehicula integer scelerisque a litora a integer ullamcorper fusce pulvinar ullamcorper ad eu. Id quis consequat venenatis suspendisse a ad turpis quam tortor id suspendisse in a venenatis sed non. Massa inceptos ante condimentum sit scelerisque ac nisl pharetra a et vestibulum cras vestibulum erat sit ad penatibus sodales blandit est dis a. Sociosqu porttitor a praesent sagittis scelerisque ad ad eu orci parturient elit tincidunt et condimentum a pretium vestibulum hendrerit a molestie blandit enim at parturient accumsan. A fermentum suspendisse class facilisis convallis cubilia quisque sociis a a vestibulum integer a class a. Scelerisque pretium a magnis id suspendisse sodales cum non cubilia parturient himenaeos sit a quisque platea magna nostra enim cras suspendisse a mi adipiscing.Consectetur a inceptos accumsan donec varius elementum conubia nec varius mi congue curabitur ante a at hac cras.Condimentum vestibulum consectetur habitant eleifend dignissim malesuada taciti a sagittis porta velit nunc elementum orci mus bibendum quisque felis sodales faucibus vehicula scelerisque a parturient.Ac hendrerit vehicula ullamcorper a parturient a quis quisque suspendisse volutpat a hac sociosqu nisl posuere mus pulvinar commodo a ullamcorper vestibulum morbi.Quis ad congue metus iaculis iaculis accumsan pretium orci vestibulum laoreet scelerisque fusce ultricies inceptos pretium consectetur.
          </Text>
          <Text variant="subtitle1" weight="700">
            Leo vulputate ullamcorper
          </Text>
          <Text variant="baseline">
            Quisque adipiscing suspendisse mus magnis scelerisque leo vulputate ullamcorper molestie in a condimentum a ac risus dictumst cum a imperdiet duis a. Primis mi erat sociosqu fringilla in cum maecenas et porta ridiculus lobortis morbi suspendisse maecenas hac dictumst dis parturient phasellus primis vestibulum a condimentum. Suscipit a placerat metus scelerisque senectus sodales ullamcorper tellus a sem senectus sed porta eleifend quam consectetur leo adipiscing curae ullamcorper erat vestibulum mauris leo quisque vestibulum id. Etiam gravida ultricies neque netus torquent tristique varius nostra sociis libero adipiscing vestibulum suspendisse scelerisque tincidunt. Facilisi nascetur laoreet eleifend adipiscing amet lobortis lacus vehicula integer scelerisque a litora a integer ullamcorper fusce pulvinar ullamcorper ad eu. Id quis consequat venenatis suspendisse a ad turpis quam tortor id suspendisse in a venenatis sed non. Massa inceptos ante condimentum sit scelerisque ac nisl pharetra a et vestibulum cras vestibulum erat sit ad penatibus sodales blandit est dis a. Sociosqu porttitor a praesent sagittis scelerisque ad ad eu orci parturient elit tincidunt et condimentum a pretium vestibulum hendrerit a molestie blandit enim at parturient accumsan. A fermentum suspendisse class facilisis convallis cubilia quisque sociis a a vestibulum integer a class a. Scelerisque pretium a magnis id suspendisse sodales cum non cubilia parturient himenaeos sit a quisque platea magna nostra enim cras suspendisse a mi adipiscing.Consectetur a inceptos accumsan donec varius elementum conubia nec varius mi congue curabitur ante a at hac cras.Condimentum vestibulum consectetur habitant eleifend dignissim malesuada taciti a sagittis porta velit nunc elementum orci mus bibendum quisque felis sodales faucibus vehicula scelerisque a parturient.Ac hendrerit vehicula ullamcorper a parturient a quis quisque suspendisse volutpat a hac sociosqu nisl posuere mus pulvinar commodo a ullamcorper vestibulum morbi.Quis ad congue metus iaculis iaculis accumsan pretium orci vestibulum laoreet scelerisque fusce ultricies inceptos pretium consectetur.
          </Text>
          <Text variant="subtitle2" weight="700">
            Condimentum a ac risus dictumst
          </Text>
          <Text variant="baseline">
            Quisque adipiscing suspendisse mus magnis scelerisque leo vulputate ullamcorper molestie in a condimentum a ac risus dictumst cum a imperdiet duis a. Primis mi erat sociosqu fringilla in cum maecenas et porta ridiculus lobortis morbi suspendisse maecenas hac dictumst dis parturient phasellus primis vestibulum a condimentum. Suscipit a placerat metus scelerisque senectus sodales ullamcorper tellus a sem senectus sed porta eleifend quam consectetur leo adipiscing curae ullamcorper erat vestibulum mauris leo quisque vestibulum id. Etiam gravida ultricies neque netus torquent tristique varius nostra sociis libero adipiscing vestibulum suspendisse scelerisque tincidunt. Facilisi nascetur laoreet eleifend adipiscing amet lobortis lacus vehicula integer scelerisque a litora a integer ullamcorper fusce pulvinar ullamcorper ad eu. Id quis consequat venenatis suspendisse a ad turpis quam tortor id suspendisse in a venenatis sed non. Massa inceptos ante condimentum sit scelerisque ac nisl pharetra a et vestibulum cras vestibulum erat sit ad penatibus sodales blandit est dis a. Sociosqu porttitor a praesent sagittis scelerisque ad ad eu orci parturient elit tincidunt et condimentum a pretium vestibulum hendrerit a molestie blandit enim at parturient accumsan. A fermentum suspendisse class facilisis convallis cubilia quisque sociis a a vestibulum integer a class a. Scelerisque pretium a magnis id suspendisse sodales cum non cubilia parturient himenaeos sit a quisque platea magna nostra enim cras suspendisse a mi adipiscing.Consectetur a inceptos accumsan donec varius elementum conubia nec varius mi congue curabitur ante a at hac cras.Condimentum vestibulum consectetur habitant eleifend dignissim malesuada taciti a sagittis porta velit nunc elementum orci mus bibendum quisque felis sodales faucibus vehicula scelerisque a parturient.Ac hendrerit vehicula ullamcorper a parturient a quis quisque suspendisse volutpat a hac sociosqu nisl posuere mus pulvinar commodo a ullamcorper vestibulum morbi.Quis ad congue metus iaculis iaculis accumsan pretium orci vestibulum laoreet scelerisque fusce ultricies inceptos pretium consectetur.
          </Text>
          <Text variant="baseline">
            Quisque adipiscing suspendisse mus magnis scelerisque leo vulputate ullamcorper molestie in a condimentum a ac risus dictumst cum a imperdiet duis a. Primis mi erat sociosqu fringilla in cum maecenas et porta ridiculus lobortis morbi suspendisse maecenas hac dictumst dis parturient phasellus primis vestibulum a condimentum. Suscipit a placerat metus scelerisque senectus sodales ullamcorper tellus a sem senectus sed porta eleifend quam consectetur leo adipiscing curae ullamcorper erat vestibulum mauris leo quisque vestibulum id. Etiam gravida ultricies neque netus torquent tristique varius nostra sociis libero adipiscing vestibulum suspendisse scelerisque tincidunt. Facilisi nascetur laoreet eleifend adipiscing amet lobortis lacus vehicula integer scelerisque a litora a integer ullamcorper fusce pulvinar ullamcorper ad eu. Id quis consequat venenatis suspendisse a ad turpis quam tortor id suspendisse in a venenatis sed non. Massa inceptos ante condimentum sit scelerisque ac nisl pharetra a et vestibulum cras vestibulum erat sit ad penatibus sodales blandit est dis a. Sociosqu porttitor a praesent sagittis scelerisque ad ad eu orci parturient elit tincidunt et condimentum a pretium vestibulum hendrerit a molestie blandit enim at parturient accumsan. A fermentum suspendisse class facilisis convallis cubilia quisque sociis a a vestibulum integer a class a. Scelerisque pretium a magnis id suspendisse sodales cum non cubilia parturient himenaeos sit a quisque platea magna nostra enim cras suspendisse a mi adipiscing.Consectetur a inceptos accumsan donec varius elementum conubia nec varius mi congue curabitur ante a at hac cras.Condimentum vestibulum consectetur habitant eleifend dignissim malesuada taciti a sagittis porta velit nunc elementum orci mus bibendum quisque felis sodales faucibus vehicula scelerisque a parturient.Ac hendrerit vehicula ullamcorper a parturient a quis quisque suspendisse volutpat a hac sociosqu nisl posuere mus pulvinar commodo a ullamcorper vestibulum morbi.Quis ad congue metus iaculis iaculis accumsan pretium orci vestibulum laoreet scelerisque fusce ultricies inceptos pretium consectetur.
          </Text>
         </ExampleContent>
      </Accordion>
      <Accordion>
        <ExampleContent>
          <Text variant="hero" weight="700">
            Quisque adipiscing
          </Text>
          <Text variant="baseline">
            Quisque adipiscing suspendisse mus magnis scelerisque leo vulputate ullamcorper molestie in a condimentum a ac risus dictumst cum a imperdiet duis a. Primis mi erat sociosqu fringilla in cum maecenas et porta ridiculus lobortis morbi suspendisse maecenas hac dictumst dis parturient phasellus primis vestibulum a condimentum. Suscipit a placerat metus scelerisque senectus sodales ullamcorper tellus a sem senectus sed porta eleifend quam consectetur leo adipiscing curae ullamcorper erat vestibulum mauris leo quisque vestibulum id. Etiam gravida ultricies neque netus torquent tristique varius nostra sociis libero adipiscing vestibulum suspendisse scelerisque tincidunt. Facilisi nascetur laoreet eleifend adipiscing amet lobortis lacus vehicula integer scelerisque a litora a integer ullamcorper fusce pulvinar ullamcorper ad eu. Id quis consequat venenatis suspendisse a ad turpis quam tortor id suspendisse in a venenatis sed non. Massa inceptos ante condimentum sit scelerisque ac nisl pharetra a et vestibulum cras vestibulum erat sit ad penatibus sodales blandit est dis a. Sociosqu porttitor a praesent sagittis scelerisque ad ad eu orci parturient elit tincidunt et condimentum a pretium vestibulum hendrerit a molestie blandit enim at parturient accumsan. A fermentum suspendisse class facilisis convallis cubilia quisque sociis a a vestibulum integer a class a. Scelerisque pretium a magnis id suspendisse sodales cum non cubilia parturient himenaeos sit a quisque platea magna nostra enim cras suspendisse a mi adipiscing.Consectetur a inceptos accumsan donec varius elementum conubia nec varius mi congue curabitur ante a at hac cras.Condimentum vestibulum consectetur habitant eleifend dignissim malesuada taciti a sagittis porta velit nunc elementum orci mus bibendum quisque felis sodales faucibus vehicula scelerisque a parturient.Ac hendrerit vehicula ullamcorper a parturient a quis quisque suspendisse volutpat a hac sociosqu nisl posuere mus pulvinar commodo a ullamcorper vestibulum morbi.Quis ad congue metus iaculis iaculis accumsan pretium orci vestibulum laoreet scelerisque fusce ultricies inceptos pretium consectetur.
          </Text>
          <Text variant="title" weight="700">
            Suspendisse mus magnis
          </Text>
          <Text variant="large">
            Quisque adipiscing suspendisse mus magnis scelerisque leo vulputate ullamcorper molestie in a condimentum a ac risus dictumst cum a imperdiet duis a. Primis mi erat sociosqu fringilla in cum maecenas et porta ridiculus lobortis morbi suspendisse maecenas hac dictumst dis parturient phasellus primis vestibulum a condimentum. Suscipit a placerat metus scelerisque senectus sodales ullamcorper tellus a sem senectus sed porta eleifend quam consectetur leo adipiscing curae ullamcorper erat vestibulum mauris leo quisque vestibulum id. Etiam gravida ultricies neque netus torquent tristique varius nostra sociis libero adipiscing vestibulum suspendisse scelerisque tincidunt. Facilisi nascetur laoreet eleifend adipiscing amet lobortis lacus vehicula integer scelerisque a litora a integer ullamcorper fusce pulvinar ullamcorper ad eu. Id quis consequat venenatis suspendisse a ad turpis quam tortor id suspendisse in a venenatis sed non. Massa inceptos ante condimentum sit scelerisque ac nisl pharetra a et vestibulum cras vestibulum erat sit ad penatibus sodales blandit est dis a. Sociosqu porttitor a praesent sagittis scelerisque ad ad eu orci parturient elit tincidunt et condimentum a pretium vestibulum hendrerit a molestie blandit enim at parturient accumsan. A fermentum suspendisse class facilisis convallis cubilia quisque sociis a a vestibulum integer a class a. Scelerisque pretium a magnis id suspendisse sodales cum non cubilia parturient himenaeos sit a quisque platea magna nostra enim cras suspendisse a mi adipiscing.Consectetur a inceptos accumsan donec varius elementum conubia nec varius mi congue curabitur ante a at hac cras.Condimentum vestibulum consectetur habitant eleifend dignissim malesuada taciti a sagittis porta velit nunc elementum orci mus bibendum quisque felis sodales faucibus vehicula scelerisque a parturient.Ac hendrerit vehicula ullamcorper a parturient a quis quisque suspendisse volutpat a hac sociosqu nisl posuere mus pulvinar commodo a ullamcorper vestibulum morbi.Quis ad congue metus iaculis iaculis accumsan pretium orci vestibulum laoreet scelerisque fusce ultricies inceptos pretium consectetur.
          </Text>
          <Text variant="subtitle1" weight="700">
            Leo vulputate ullamcorper
          </Text>
          <Text variant="baseline">
            Quisque adipiscing suspendisse mus magnis scelerisque leo vulputate ullamcorper molestie in a condimentum a ac risus dictumst cum a imperdiet duis a. Primis mi erat sociosqu fringilla in cum maecenas et porta ridiculus lobortis morbi suspendisse maecenas hac dictumst dis parturient phasellus primis vestibulum a condimentum. Suscipit a placerat metus scelerisque senectus sodales ullamcorper tellus a sem senectus sed porta eleifend quam consectetur leo adipiscing curae ullamcorper erat vestibulum mauris leo quisque vestibulum id. Etiam gravida ultricies neque netus torquent tristique varius nostra sociis libero adipiscing vestibulum suspendisse scelerisque tincidunt. Facilisi nascetur laoreet eleifend adipiscing amet lobortis lacus vehicula integer scelerisque a litora a integer ullamcorper fusce pulvinar ullamcorper ad eu. Id quis consequat venenatis suspendisse a ad turpis quam tortor id suspendisse in a venenatis sed non. Massa inceptos ante condimentum sit scelerisque ac nisl pharetra a et vestibulum cras vestibulum erat sit ad penatibus sodales blandit est dis a. Sociosqu porttitor a praesent sagittis scelerisque ad ad eu orci parturient elit tincidunt et condimentum a pretium vestibulum hendrerit a molestie blandit enim at parturient accumsan. A fermentum suspendisse class facilisis convallis cubilia quisque sociis a a vestibulum integer a class a. Scelerisque pretium a magnis id suspendisse sodales cum non cubilia parturient himenaeos sit a quisque platea magna nostra enim cras suspendisse a mi adipiscing.Consectetur a inceptos accumsan donec varius elementum conubia nec varius mi congue curabitur ante a at hac cras.Condimentum vestibulum consectetur habitant eleifend dignissim malesuada taciti a sagittis porta velit nunc elementum orci mus bibendum quisque felis sodales faucibus vehicula scelerisque a parturient.Ac hendrerit vehicula ullamcorper a parturient a quis quisque suspendisse volutpat a hac sociosqu nisl posuere mus pulvinar commodo a ullamcorper vestibulum morbi.Quis ad congue metus iaculis iaculis accumsan pretium orci vestibulum laoreet scelerisque fusce ultricies inceptos pretium consectetur.
          </Text>
          <Text variant="subtitle2" weight="700">
            Condimentum a ac risus dictumst
          </Text>
          <Text variant="baseline">
            Quisque adipiscing suspendisse mus magnis scelerisque leo vulputate ullamcorper molestie in a condimentum a ac risus dictumst cum a imperdiet duis a. Primis mi erat sociosqu fringilla in cum maecenas et porta ridiculus lobortis morbi suspendisse maecenas hac dictumst dis parturient phasellus primis vestibulum a condimentum. Suscipit a placerat metus scelerisque senectus sodales ullamcorper tellus a sem senectus sed porta eleifend quam consectetur leo adipiscing curae ullamcorper erat vestibulum mauris leo quisque vestibulum id. Etiam gravida ultricies neque netus torquent tristique varius nostra sociis libero adipiscing vestibulum suspendisse scelerisque tincidunt. Facilisi nascetur laoreet eleifend adipiscing amet lobortis lacus vehicula integer scelerisque a litora a integer ullamcorper fusce pulvinar ullamcorper ad eu. Id quis consequat venenatis suspendisse a ad turpis quam tortor id suspendisse in a venenatis sed non. Massa inceptos ante condimentum sit scelerisque ac nisl pharetra a et vestibulum cras vestibulum erat sit ad penatibus sodales blandit est dis a. Sociosqu porttitor a praesent sagittis scelerisque ad ad eu orci parturient elit tincidunt et condimentum a pretium vestibulum hendrerit a molestie blandit enim at parturient accumsan. A fermentum suspendisse class facilisis convallis cubilia quisque sociis a a vestibulum integer a class a. Scelerisque pretium a magnis id suspendisse sodales cum non cubilia parturient himenaeos sit a quisque platea magna nostra enim cras suspendisse a mi adipiscing.Consectetur a inceptos accumsan donec varius elementum conubia nec varius mi congue curabitur ante a at hac cras.Condimentum vestibulum consectetur habitant eleifend dignissim malesuada taciti a sagittis porta velit nunc elementum orci mus bibendum quisque felis sodales faucibus vehicula scelerisque a parturient.Ac hendrerit vehicula ullamcorper a parturient a quis quisque suspendisse volutpat a hac sociosqu nisl posuere mus pulvinar commodo a ullamcorper vestibulum morbi.Quis ad congue metus iaculis iaculis accumsan pretium orci vestibulum laoreet scelerisque fusce ultricies inceptos pretium consectetur.
          </Text>
          <Text variant="baseline">
            Quisque adipiscing suspendisse mus magnis scelerisque leo vulputate ullamcorper molestie in a condimentum a ac risus dictumst cum a imperdiet duis a. Primis mi erat sociosqu fringilla in cum maecenas et porta ridiculus lobortis morbi suspendisse maecenas hac dictumst dis parturient phasellus primis vestibulum a condimentum. Suscipit a placerat metus scelerisque senectus sodales ullamcorper tellus a sem senectus sed porta eleifend quam consectetur leo adipiscing curae ullamcorper erat vestibulum mauris leo quisque vestibulum id. Etiam gravida ultricies neque netus torquent tristique varius nostra sociis libero adipiscing vestibulum suspendisse scelerisque tincidunt. Facilisi nascetur laoreet eleifend adipiscing amet lobortis lacus vehicula integer scelerisque a litora a integer ullamcorper fusce pulvinar ullamcorper ad eu. Id quis consequat venenatis suspendisse a ad turpis quam tortor id suspendisse in a venenatis sed non. Massa inceptos ante condimentum sit scelerisque ac nisl pharetra a et vestibulum cras vestibulum erat sit ad penatibus sodales blandit est dis a. Sociosqu porttitor a praesent sagittis scelerisque ad ad eu orci parturient elit tincidunt et condimentum a pretium vestibulum hendrerit a molestie blandit enim at parturient accumsan. A fermentum suspendisse class facilisis convallis cubilia quisque sociis a a vestibulum integer a class a. Scelerisque pretium a magnis id suspendisse sodales cum non cubilia parturient himenaeos sit a quisque platea magna nostra enim cras suspendisse a mi adipiscing.Consectetur a inceptos accumsan donec varius elementum conubia nec varius mi congue curabitur ante a at hac cras.Condimentum vestibulum consectetur habitant eleifend dignissim malesuada taciti a sagittis porta velit nunc elementum orci mus bibendum quisque felis sodales faucibus vehicula scelerisque a parturient.Ac hendrerit vehicula ullamcorper a parturient a quis quisque suspendisse volutpat a hac sociosqu nisl posuere mus pulvinar commodo a ullamcorper vestibulum morbi.Quis ad congue metus iaculis iaculis accumsan pretium orci vestibulum laoreet scelerisque fusce ultricies inceptos pretium consectetur.
          </Text>
         </ExampleContent>
      </Accordion>
      <Accordion>
        <ExampleContent>
          <Text variant="hero" weight="700">
            Quisque adipiscing
          </Text>
          <Text variant="baseline">
            Quisque adipiscing suspendisse mus magnis scelerisque leo vulputate ullamcorper molestie in a condimentum a ac risus dictumst cum a imperdiet duis a. Primis mi erat sociosqu fringilla in cum maecenas et porta ridiculus lobortis morbi suspendisse maecenas hac dictumst dis parturient phasellus primis vestibulum a condimentum. Suscipit a placerat metus scelerisque senectus sodales ullamcorper tellus a sem senectus sed porta eleifend quam consectetur leo adipiscing curae ullamcorper erat vestibulum mauris leo quisque vestibulum id. Etiam gravida ultricies neque netus torquent tristique varius nostra sociis libero adipiscing vestibulum suspendisse scelerisque tincidunt. Facilisi nascetur laoreet eleifend adipiscing amet lobortis lacus vehicula integer scelerisque a litora a integer ullamcorper fusce pulvinar ullamcorper ad eu. Id quis consequat venenatis suspendisse a ad turpis quam tortor id suspendisse in a venenatis sed non. Massa inceptos ante condimentum sit scelerisque ac nisl pharetra a et vestibulum cras vestibulum erat sit ad penatibus sodales blandit est dis a. Sociosqu porttitor a praesent sagittis scelerisque ad ad eu orci parturient elit tincidunt et condimentum a pretium vestibulum hendrerit a molestie blandit enim at parturient accumsan. A fermentum suspendisse class facilisis convallis cubilia quisque sociis a a vestibulum integer a class a. Scelerisque pretium a magnis id suspendisse sodales cum non cubilia parturient himenaeos sit a quisque platea magna nostra enim cras suspendisse a mi adipiscing.Consectetur a inceptos accumsan donec varius elementum conubia nec varius mi congue curabitur ante a at hac cras.Condimentum vestibulum consectetur habitant eleifend dignissim malesuada taciti a sagittis porta velit nunc elementum orci mus bibendum quisque felis sodales faucibus vehicula scelerisque a parturient.Ac hendrerit vehicula ullamcorper a parturient a quis quisque suspendisse volutpat a hac sociosqu nisl posuere mus pulvinar commodo a ullamcorper vestibulum morbi.Quis ad congue metus iaculis iaculis accumsan pretium orci vestibulum laoreet scelerisque fusce ultricies inceptos pretium consectetur.
          </Text>
          <Text variant="title" weight="700">
            Suspendisse mus magnis
          </Text>
          <Text variant="large">
            Quisque adipiscing suspendisse mus magnis scelerisque leo vulputate ullamcorper molestie in a condimentum a ac risus dictumst cum a imperdiet duis a. Primis mi erat sociosqu fringilla in cum maecenas et porta ridiculus lobortis morbi suspendisse maecenas hac dictumst dis parturient phasellus primis vestibulum a condimentum. Suscipit a placerat metus scelerisque senectus sodales ullamcorper tellus a sem senectus sed porta eleifend quam consectetur leo adipiscing curae ullamcorper erat vestibulum mauris leo quisque vestibulum id. Etiam gravida ultricies neque netus torquent tristique varius nostra sociis libero adipiscing vestibulum suspendisse scelerisque tincidunt. Facilisi nascetur laoreet eleifend adipiscing amet lobortis lacus vehicula integer scelerisque a litora a integer ullamcorper fusce pulvinar ullamcorper ad eu. Id quis consequat venenatis suspendisse a ad turpis quam tortor id suspendisse in a venenatis sed non. Massa inceptos ante condimentum sit scelerisque ac nisl pharetra a et vestibulum cras vestibulum erat sit ad penatibus sodales blandit est dis a. Sociosqu porttitor a praesent sagittis scelerisque ad ad eu orci parturient elit tincidunt et condimentum a pretium vestibulum hendrerit a molestie blandit enim at parturient accumsan. A fermentum suspendisse class facilisis convallis cubilia quisque sociis a a vestibulum integer a class a. Scelerisque pretium a magnis id suspendisse sodales cum non cubilia parturient himenaeos sit a quisque platea magna nostra enim cras suspendisse a mi adipiscing.Consectetur a inceptos accumsan donec varius elementum conubia nec varius mi congue curabitur ante a at hac cras.Condimentum vestibulum consectetur habitant eleifend dignissim malesuada taciti a sagittis porta velit nunc elementum orci mus bibendum quisque felis sodales faucibus vehicula scelerisque a parturient.Ac hendrerit vehicula ullamcorper a parturient a quis quisque suspendisse volutpat a hac sociosqu nisl posuere mus pulvinar commodo a ullamcorper vestibulum morbi.Quis ad congue metus iaculis iaculis accumsan pretium orci vestibulum laoreet scelerisque fusce ultricies inceptos pretium consectetur.
          </Text>
          <Text variant="subtitle1" weight="700">
            Leo vulputate ullamcorper
          </Text>
          <Text variant="baseline">
            Quisque adipiscing suspendisse mus magnis scelerisque leo vulputate ullamcorper molestie in a condimentum a ac risus dictumst cum a imperdiet duis a. Primis mi erat sociosqu fringilla in cum maecenas et porta ridiculus lobortis morbi suspendisse maecenas hac dictumst dis parturient phasellus primis vestibulum a condimentum. Suscipit a placerat metus scelerisque senectus sodales ullamcorper tellus a sem senectus sed porta eleifend quam consectetur leo adipiscing curae ullamcorper erat vestibulum mauris leo quisque vestibulum id. Etiam gravida ultricies neque netus torquent tristique varius nostra sociis libero adipiscing vestibulum suspendisse scelerisque tincidunt. Facilisi nascetur laoreet eleifend adipiscing amet lobortis lacus vehicula integer scelerisque a litora a integer ullamcorper fusce pulvinar ullamcorper ad eu. Id quis consequat venenatis suspendisse a ad turpis quam tortor id suspendisse in a venenatis sed non. Massa inceptos ante condimentum sit scelerisque ac nisl pharetra a et vestibulum cras vestibulum erat sit ad penatibus sodales blandit est dis a. Sociosqu porttitor a praesent sagittis scelerisque ad ad eu orci parturient elit tincidunt et condimentum a pretium vestibulum hendrerit a molestie blandit enim at parturient accumsan. A fermentum suspendisse class facilisis convallis cubilia quisque sociis a a vestibulum integer a class a. Scelerisque pretium a magnis id suspendisse sodales cum non cubilia parturient himenaeos sit a quisque platea magna nostra enim cras suspendisse a mi adipiscing.Consectetur a inceptos accumsan donec varius elementum conubia nec varius mi congue curabitur ante a at hac cras.Condimentum vestibulum consectetur habitant eleifend dignissim malesuada taciti a sagittis porta velit nunc elementum orci mus bibendum quisque felis sodales faucibus vehicula scelerisque a parturient.Ac hendrerit vehicula ullamcorper a parturient a quis quisque suspendisse volutpat a hac sociosqu nisl posuere mus pulvinar commodo a ullamcorper vestibulum morbi.Quis ad congue metus iaculis iaculis accumsan pretium orci vestibulum laoreet scelerisque fusce ultricies inceptos pretium consectetur.
          </Text>
          <Text variant="subtitle2" weight="700">
            Condimentum a ac risus dictumst
          </Text>
          <Text variant="baseline">
            Quisque adipiscing suspendisse mus magnis scelerisque leo vulputate ullamcorper molestie in a condimentum a ac risus dictumst cum a imperdiet duis a. Primis mi erat sociosqu fringilla in cum maecenas et porta ridiculus lobortis morbi suspendisse maecenas hac dictumst dis parturient phasellus primis vestibulum a condimentum. Suscipit a placerat metus scelerisque senectus sodales ullamcorper tellus a sem senectus sed porta eleifend quam consectetur leo adipiscing curae ullamcorper erat vestibulum mauris leo quisque vestibulum id. Etiam gravida ultricies neque netus torquent tristique varius nostra sociis libero adipiscing vestibulum suspendisse scelerisque tincidunt. Facilisi nascetur laoreet eleifend adipiscing amet lobortis lacus vehicula integer scelerisque a litora a integer ullamcorper fusce pulvinar ullamcorper ad eu. Id quis consequat venenatis suspendisse a ad turpis quam tortor id suspendisse in a venenatis sed non. Massa inceptos ante condimentum sit scelerisque ac nisl pharetra a et vestibulum cras vestibulum erat sit ad penatibus sodales blandit est dis a. Sociosqu porttitor a praesent sagittis scelerisque ad ad eu orci parturient elit tincidunt et condimentum a pretium vestibulum hendrerit a molestie blandit enim at parturient accumsan. A fermentum suspendisse class facilisis convallis cubilia quisque sociis a a vestibulum integer a class a. Scelerisque pretium a magnis id suspendisse sodales cum non cubilia parturient himenaeos sit a quisque platea magna nostra enim cras suspendisse a mi adipiscing.Consectetur a inceptos accumsan donec varius elementum conubia nec varius mi congue curabitur ante a at hac cras.Condimentum vestibulum consectetur habitant eleifend dignissim malesuada taciti a sagittis porta velit nunc elementum orci mus bibendum quisque felis sodales faucibus vehicula scelerisque a parturient.Ac hendrerit vehicula ullamcorper a parturient a quis quisque suspendisse volutpat a hac sociosqu nisl posuere mus pulvinar commodo a ullamcorper vestibulum morbi.Quis ad congue metus iaculis iaculis accumsan pretium orci vestibulum laoreet scelerisque fusce ultricies inceptos pretium consectetur.
          </Text>
          <Text variant="baseline">
            Quisque adipiscing suspendisse mus magnis scelerisque leo vulputate ullamcorper molestie in a condimentum a ac risus dictumst cum a imperdiet duis a. Primis mi erat sociosqu fringilla in cum maecenas et porta ridiculus lobortis morbi suspendisse maecenas hac dictumst dis parturient phasellus primis vestibulum a condimentum. Suscipit a placerat metus scelerisque senectus sodales ullamcorper tellus a sem senectus sed porta eleifend quam consectetur leo adipiscing curae ullamcorper erat vestibulum mauris leo quisque vestibulum id. Etiam gravida ultricies neque netus torquent tristique varius nostra sociis libero adipiscing vestibulum suspendisse scelerisque tincidunt. Facilisi nascetur laoreet eleifend adipiscing amet lobortis lacus vehicula integer scelerisque a litora a integer ullamcorper fusce pulvinar ullamcorper ad eu. Id quis consequat venenatis suspendisse a ad turpis quam tortor id suspendisse in a venenatis sed non. Massa inceptos ante condimentum sit scelerisque ac nisl pharetra a et vestibulum cras vestibulum erat sit ad penatibus sodales blandit est dis a. Sociosqu porttitor a praesent sagittis scelerisque ad ad eu orci parturient elit tincidunt et condimentum a pretium vestibulum hendrerit a molestie blandit enim at parturient accumsan. A fermentum suspendisse class facilisis convallis cubilia quisque sociis a a vestibulum integer a class a. Scelerisque pretium a magnis id suspendisse sodales cum non cubilia parturient himenaeos sit a quisque platea magna nostra enim cras suspendisse a mi adipiscing.Consectetur a inceptos accumsan donec varius elementum conubia nec varius mi congue curabitur ante a at hac cras.Condimentum vestibulum consectetur habitant eleifend dignissim malesuada taciti a sagittis porta velit nunc elementum orci mus bibendum quisque felis sodales faucibus vehicula scelerisque a parturient.Ac hendrerit vehicula ullamcorper a parturient a quis quisque suspendisse volutpat a hac sociosqu nisl posuere mus pulvinar commodo a ullamcorper vestibulum morbi.Quis ad congue metus iaculis iaculis accumsan pretium orci vestibulum laoreet scelerisque fusce ultricies inceptos pretium consectetur.
          </Text>
         </ExampleContent>
      </Accordion>
    </div>
  ));


const ExampleContent = styled.div`
  width: 100%;
  padding: 2rem;

  & > div {
    margin: 0 0 2rem;

    &:last-of-type {
      margin: 0;
    }
  }
`;